name: LastMobStanding
main: pe.chalk.bukkit.LastMobStanding
version: 1.0-SNAPSHOT

depend: [iDisguise]

permissions:
  lastmobstanding.use:
    description: Allows you to control game
    default: op

commands:
  lms:
    description: Last Mob Standing
    aliases: [lastmob, lastmobstanding]
    permission: lastmobstanding.use
    usage: "Usage: /lms [start | stop | status]"